### ISSUE TITLE
prep_sector_dat not removing capitals from process names

### ISSUE THREAD

**Issue by todd-davidson-beis** [DataScienceScotland/vedar#67]
https://github.com/DataScienceScotland/vedar/blob/0d45a8155c3710d9cc2f9a85879bc1ce2974f560/R/get_veda_dat.R#L231

I think this needs to change from:

  sector_dat %>%
    #strings to lower
    dplyr::mutate_if(is.character, stringr::str_to_lower)

to:

sector_dat <-  sector_dat %>%
    #strings to lower
    dplyr::mutate_if(is.character, stringr::str_to_lower)

Otherwise the mutate output is not being stored anywhere?

(Sorry if this is in the wrong place, I don't know how to use GitHub!)

**Comment by irisoren-sg** [comment]
Thanks @todd-davidson-beis. I added your suggested fix. That should now be working
