### ISSUE TITLE
make_res requires dat to have a sector column

### ISSUE THREAD

**Issue by todd-davidson-beis** [DataScienceScotland/vedar#68]
https://github.com/DataScienceScotland/vedar/blob/0d45a8155c3710d9cc2f9a85879bc1ce2974f560/R/network_analysis.R#L45
>      if(sector_select %in% dat$sector == F){

The column name for the sectors is hardcoded here - whereas in my messing around I have a process_sector and a commodity_sector, much like the example output of define_sector_from_list which has the column name process_major_sector.

There are also many cases where process_sector and commodity_sector don't match, so not easy to know which to pick. Probably process_sector, as the Sankey diagram has the commodities as flows between processes?

**Comment by irisoren-sg** [comment]
@todd-davidson-beis Just to clarify, you are wanting to be able to pass the name of the sector column to make_res, and then specify the value of that sector to plot?
I will create a separate issue for this. But a work-around is to preprocess the data and rename your column (say process_sector) to sector.

**Comment by todd-davidson-beis** [comment]
Thanks for chasing me, Iris - sorry, this fell by the wayside a little.

I did have a go at editing a bit of the code and doing a pull_request, but I think that requires me to make a branch first, which requires more access permissions to the repository that I currently have?

As for make_res, yes, you're right, I am currently using it with dat %>% rename(sector = process_sector) as the input, but your suggestion is essentially what I was thinking:

make_res <- function(dat, period_select = NULL,
                    name_of_sector_column = "sector",
                     sector_select = NULL,
                     region_select = NULL,
                     node_labels = process_description,
                     edge_labels = commodity_description,
                     sankey_width = NULL,
                     sankey_height = NULL,
                     font_size = 10)

I guess the real issue is that the output of define_sector_from_list cannot be an input to make_res because define_sector creates columns called, e.g., 'process_sector' or 'commodity_sector', and make_res is expecting something called just 'sector'.

But maybe it's weird that I am making a commodity_sector column? Maybe the output of define_sector_from_list should just be a column called 'sector', and any user will naturally only label by the process' sector? (For a given line in dat, the commodity_sector and process_sector often disagree, e.g., a commodity from the resources or agriculture or processing sector being used in the electricity or residential sector.)

Interested to hear your thoughts!
Todd

**Comment by irisoren-sg** [comment]
@todd-davidson-beis Continuing the discussion on the (page for the new issue)
[https://github.com/DataScienceScotland/vedar/issues/75]

**Comment by irisoren-sg** [comment]
@todd-davidson-beis  As to making a pull request, you should be able to make a PR from a fork

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
